WIP Add exporting with argument device affinities
nod-ai/SHARK-Platform pull request #300
Opened 2024-10-21 19:37 UTC by sogartar

We don't have handling of device affinties for our sharded tensor types when they are the arguments of exported functions. Although, they can be specified explicitly when exporting, this change adds the ability to hide this and deduces the affinties from the tensor types.

2024-10-21 19:41 UTC, sogartar commented
This requires https://github.com/iree-org/iree-turbine/pull/231.

2024-10-22 17:43 UTC, rsuderman requested changes

2024-10-22 17:43 UTC, rsuderman commented on sharktank/sharktank/export.py
> +            argument_device_affinities=argument_device_affinities,
Wait, where does this actually plumb through? I don't see this as part of the PR

2024-10-22 17:51 UTC, rsuderman commented on sharktank/sharktank/export.py
> +            argument_device_affinities=argument_device_affinities,
I see, the changes are dependent on https://github.com/iree-org/iree-turbine/pull/231/files
Lets focus on that and shelve these changes. Once `export` has the right parameter we won't need to make the sharktank changes.

2024-10-23 22:42 UTC, rsuderman approved these changes

2024-10-23 23:26 UTC, merged