Fix different --bs=1 behavior confusing many people
nod-ai/SHARK-Platform pull request #328
Opened 2024-10-24 23:05 UTC by renxida

2024-10-24 23:46 UTC, dan-garvey requested changes
Lets move this flag to the cli.py file so it can be shared and not repeated. Also, iirc paged is probably not required in the bs1 case?

2024-10-24 23:46 UTC, dan-garvey commented on sharktank/sharktank/examples/export_paged_llm_v1.py
> +        default="paged",
duplicate

2024-10-25 14:44 UTC, ScottTodd commented on sharktank/sharktank/examples/export_paged_llm_v1.py
My general feeling with this script is that it is due for a rewrite. That might just involve splitting into separate scripts, one entry point for each model / variant, or something more like a fully self-contained model import pipeline from HF/GGUF --> MLIR --> VMFB+IRPA.

What users will expect is a simple process to follow for off-the-shelf and custom models that produces files which are ready for serving via shortfin. Whatever we need to do with cache types, batch sizes, etc. to get no errors, good accuracy, and good performance should all be handled for the user on the default path. For power users, we can expose tuning and customization options.

2024-10-25 16:28 UTC, gpetters-amd commented on sharktank/sharktank/examples/export_paged_llm_v1.py
> or something more like a fully self-contained model import pipeline from HF/GGUF --> MLIR --> VMFB+IRPA.

Are you envisioning something like turbine-models' export scripts or something more akin to an SD pipeline class? I've refactored some of the export_paged_llm_v1 code into a dirty export script I've been working off of that I can clean up if that's the direction we want to move toward.

2024-10-25 18:51 UTC, renxida commented
Superceded by #330 thanks Dan!

2024-10-28 15:35 UTC, ScottTodd commented on sharktank/sharktank/examples/export_paged_llm_v1.py
I'm thinking of something between what we have today and https://docs.vllm.ai/en/latest/getting_started/quickstart.html#offline-batched-inference

![image](https://github.com/user-attachments/assets/891ee59b-1167-4609-9c65-a54f2b473234)

or https://nvidia.github.io/TensorRT-LLM/quick-start-guide.html
![image](https://github.com/user-attachments/assets/7ab6232c-8b92-4710-a805-7d16287226e8)

2024-10-29 19:53 UTC, closed without merging